const BYTE_CONSTANT =  {
    FIRST_BIT_VALUE: 128,
    MAXIMUM_SIXTEEN_BITS_VALUE: 2 ** 16,
    MAXIMUM_SIXTY_FOUR_BITS_VALUE: 8 ** 16,
}

const SOCKET_CONSTANT =  {
   MASK_KEY: {
       BYTES: 4,
   },
   MAGIC_STRING: '258EAFA5-E914-47DA-95CA-C5AB0DC85B11'
}



export {
    BYTE_CONSTANT,
    SOCKET_CONSTANT
}
